apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeport-test
  labels:
    app: backend
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-test
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
