apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: "Update image to nginx:alpine"
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 110
