apiVersion: v1
kind: Pod
metadata:
  name: pod-test-2
spec:
  containers:
  - name: container-1
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test-3
spec:
  containers:
  - name: container-1
    image: nginx:alpine