apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
  labels:
    app: rs-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      name: pod-test-2-cont
      labels:
        app: pod-label
    spec:
      containers:
      - name: container-1
        image: python:3.7-alpine
        command: ['sh', '-c', 'echo container-1 > index.html && python -m http.server 8082']
